export const ExperienceContent = [
  {
    company: "Neardeals",
    link: "",
    role: "Senior Software Engineer",
    time: "10/2023 – Present",
    location: "Dhaka, Bangladesh (Remote)",
    brief: [
      "Led the development of high-quality e-commerce mobile applications using Flutter.",
      "Managed full lifecycle of application development, from requirements to deployment.",
      "Collaborated with cross-functional teams for feature design and API integration.",
      "Regularly updated apps with new features and performance enhancements.",
      "Conducted thorough code reviews to ensure code quality and best practices.",
    ],
  },
  {
    company: "Entrust BD",
    link: "http://www.entrust-bd.com/",
    role: "Senior Software Engineer",
    time: "02/2023 – 09/2023",
    location: "Dhaka, Bangladesh (Remote)",
    brief: [
      "Led the development and implementation of three projects.",
      "Collaborated closely with cross-functional teams to gather requirements and design the solution.",
      "Designed and developed mobile and web applications based on client requirements.",
      "Deployed mobile and web applications.",
    ],
  },
  {
    company: "Zuellig Pharma",
    link: "",
    role: "Mobile Application Developer",
    time: "12/2021 – 02/2023",
    location: "Singapore (Remote)",
    brief: [
      "Actively worked in an agile software development environment utilizing the Scrum process.",
      "Maintained existing mobile and front-end applications.",
      "Performed UAT to confirm that the software meets client requirements.",
      "Collaborated with designers and product managers to translate wireframes into functional mobile applications.",
      "Provided prompt solutions and troubleshooting support for production issues.",
      "Prepared and deployed app builds to the stores.",
    ],
  },
  {
    company: "Fanion",
    link: "",
    role: "Mobile Application Developer",
    time: "05/2021 – 01/2022",
    location: "France (Remote)",
    brief: [
      "Developed and maintained mobile applications for Android and iOS.",
      "Added new features, fixed bugs, and improved performance.",
      "Conducted user acceptance testing.",
      "Prepared and deployed app builds to the stores.",
    ],
  },
  {
    company: "Kludio Asia Ltd.",
    link: "",
    role: "Mobile Application Developer",
    time: "04/2020 – 05/2021",
    location: "Dhaka, Bangladesh (Remote)",
    brief: [
      "Created a mobile application with 1,000+ daily users and 10K+ downloads.",
      "Added new features, fixed bugs, and improved performance.",
      "Worked alongside other developers following Sprint-based Agile methodology.",
    ],
  },
  {
    company: "KickBack Inc.",
    link: "",
    role: "Software Engineer",
    time: "10/2018 – 10/2020",
    location: "Dhaka, Bangladesh",
    brief: [
      "Created and maintained Android (native & cross-platform), frontend, and backend applications.",
      "Developed three native Android apps, one Flutter app, three ReactJS admin panels, and one Node.js backend.",
      "Updated and refactored legacy project codebases.",
    ],
  },
  {
    company: "Audacity IT Solutions Ltd.",
    link: "",
    role: "Android Developer",
    time: "07/2017 – 09/2018",
    location: "Dhaka, Bangladesh",
    brief: [
      "Worked on 5+ native Android applications with UI and functionality.",
      "Developed cross-platform (Android & iOS) applications using Flutter.",
      "Collaborated with clients to implement features and solve issues.",
      "Conducted requirement analysis and project estimation.",
    ],
  },
  {
    company: "RRMSENSE Global Systech Ltd.",
    link: "",
    role: "Android Developer",
    time: "02/2017 – 07/2017",
    location: "Dhaka, Bangladesh",
    brief: [
      "Developed 3+ Android applications including UI and functionality.",
      "Worked on IoT R&D projects for home automation.",
      "Prepared project requirements and functionality for in-house applications.",
    ],
  },
  {
    company: "Entrust BD",
    link: "http://www.entrust-bd.com/",
    role: "Software Developer",
    time: "03/2016 – 12/2016",
    location: "Dhaka, Bangladesh",
    brief: [
      "Developed 2+ Android and web applications.",
      "Prepared R&D projects to analyze project scope and feasibility.",
      "Communicated with clients for project requirements.",
    ],
  },
  {
    company: "Revo Interactive",
    link: "",
    role: "Junior Software Developer",
    time: "09/2014 – 10/2015",
    location: "Dhaka, Bangladesh",
    brief: [
      "Developed 2+ games using Unity3D and Adobe Flash for mobile platforms.",
      "Conducted user acceptance testing on released products.",
      "Experimented with various AR/VR applications.",
    ],
  },
];
